### ISSUE TITLE
US-2: View/Modify/Cancel a reservation

### ISSUE THREAD

**Issue by kidtoxic** [sknt11/Orion-soen341projectW2024#2]
User Story Description

As a customer, I want to be able to view, modify and cancel a reservation on the website so that I can stay informed and modify in case of any changes.

User Acceptance Flow

1.  User presses on the View Reservation (button or displayed another way)
2.  Website displays the information about the reservation
3.  User is given two options to either Cancel or Modify Reservation (buttons)
4. Update the information depending on user input 

Acceptance Criteria

- [x] User Acceptance Flow is respected 
- [x] The data of reservation should be saved when making a reservation Task-1
- [x] Reservation data updated within the database 
- [x] Documentation present where necessary 
- [x] Unit and UI tests are implemented for every new component and function
- [x] The application should still work with seeded data

**Comment by matiakc** [comment]
![US2 Sequence diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/24ae2cbf-c798-44cf-a657-0900806e8ef1)

**Comment by khaledrezgui** [comment]
Done by Khaled.
