### ISSUE TITLE
US-7: Find Branch

### ISSUE THREAD

**Issue by sknt11** [sknt11/Orion-soen341projectW2024#33]
User Story Description

As a customer, I want to be able to find the nearest branch so that I can easily rent a car.

User Acceptance Flow

    User Selects the option to find branch
    Prompt the user to enter preferred branch location
    Display available branches that match the user's criteria.

Acceptance Criteria

- [x] Task 7.1 User can search branch by location
- [x] Task 7.2 User can view branch details such as location, contact info, and available cars

**Comment by matiakc** [comment]
![US7 Activity diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/88bd50a1-7850-41f6-bf7f-382b474c6fe4)

**Comment by matiakc** [comment]
![US7 Sequence Diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/4a85ae78-9204-4fe7-9ba3-53b41be53053)

**Comment by matiakc** [comment]
Firstly, the user either signs in or logs in to the authentication route. Once the user is logged in, the user may search for branches. Note that the user can only search for branches once he is logged into the system. Once the user selects a branch, the branch selected by the user has corresponding cars available to it, so when the user searches for a car, the branch performs the search in its own catalogue using branchID. Next, from the displayed search, the user selects the vehicle he desires. Once the vehicle is selected, the branch checks the details of the car and then sends the data to the user. The user then picks a rental by giving a period that he wishes to have the car for. The selected car must then check in the reservations database whether the exists a reservation for that car at the selected time, and if there doesn’t exist one, the user is free to book that car. The user then can confirm the booking by creating a reservation. Once the reservation is booked, the user provides payment information to the branch, and once the payment passes, the branch sends the user a confirmation of the reservation (through email).
