### ISSUE TITLE
US-8: Check-In Process

### ISSUE THREAD

**Issue by sknt11** [sknt11/Orion-soen341projectW2024#34]
User Story Description

As a customer, I want to be able to check-in at my preferred branch so that I can provide my reservation details and make a reservation

User Acceptance Flow

Prompt the user to enter necessary details for the reservation, such as user name, branch, and reservation ID.
Upon check-in, a confirmation message of check-in success is displayed.
User can view all cars available at branch and select preferred car.
User reviews the summary of their reservation details and confirms the booking.
Confirm the reservation and provide a reservation number or confirmation detail to the user.

Acceptance Criteria

- [x] Task 8.1  User can check in branch
- [x] Task 8.2 User gets confirmation whether check-in was successful
- [x] Task 8.3 User views available cars at branch

[rentalagreement..pdf](https://github.com/sknt11/Orion-soen341projectW2024/files/14798029/rentalagreement.pdf)

**Comment by matiakc** [comment]
![US8 Activity Diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/dafb3de9-0583-4331-802a-52ede6ad839f)

**Comment by matiakc** [comment]
![US8 Sequence diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/363c17a8-1a1f-4c41-81b2-fba42efaa799)

**Comment by matiakc** [comment]
First, the user arrives at the designated branch with the required documentation. The arrival of the user is confirmed on the software by an admin user (the employee at the branch) modifying the status of the car that is being rented. Next the user (the client) inspects the car. Upon successful inspection, the admin user confirms on the software that the client confirmed no damage to the car by modifying the status of the reservation. Next, the rental agreement is signed, and the user (client) sends the signed contract to the reservation database. Next, the system takes the deposit from the user, which is done on a third-party banking service, and finally, once the user drives away with the car, the admin user confirms on the application that the car has been driven away.

**Comment by khaledrezgui** [comment]
[rentalagreement..pdf](https://github.com/sknt11/Orion-soen341projectW2024/files/14798029/rentalagreement.pdf)

**Comment by khaledrezgui** [comment]
Feature implemented in sprint 3 with help of Safaa.
