### ISSUE TITLE
US - 9: Check-Out Process

### ISSUE THREAD

**Issue by sknt11** [sknt11/Orion-soen341projectW2024#35]
User Story Description

As a customer, I want to be able to check-out at my preferred branch so that I can pay for and complete my car reservation.

User Acceptance Flow

Prompt the user to enter location where the car will be returned
Upon check-out, a confirmation message of check-in success is displayed.
User reviews the summary of their reservation cost and details.
User can fill payment form to complete reservation.
User gets a confirmation message upon successful payment.

Acceptance Criteria

- [x] Task 9.1  User can check out branch
- [x] Task 9.2 User gets confirmation whether check-out was successful
- [x] Task 9.3 User views reservation summary 
- [x] Task 9.4 User can pay online at check-out

**Comment by matiakc** [comment]
![US9 Activity diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/18c37dff-697d-4928-ba57-77998a50a27a)

**Comment by matiakc** [comment]
![US9 Sequence diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/bbd7abf3-a611-43f8-94e5-9d834e79c290)

**Comment by matiakc** [comment]
First, the user returns the car, and an admin user confirms the return by changing the reservation status of that car. Next, the user performs a payment to the third-party banking system, which then confirms payment to the reservation. Next, the reservation system automatically sends a request to the banking system to reimburse the initial deposit to the user. Note that the user must first pay for the rental of the car before the deposit is returned. Therefore, both the car must be free of damage and the payment has to be made in order for the 500CAD deposit to be returned to the user.

**Comment by khaledrezgui** [comment]
Feature implemented.
