### ISSUE TITLE
US-4: CRUD operations on users

### ISSUE THREAD

**Issue by jae-don** [sknt11/Orion-soen341projectW2024#4]
User Story Description

As a system admin, I want to perform Create, Read, Update and Delete operations on user accounts so that I can manage user information efficiently. 

User Acceptance Flow

1. System administrator logs into the portal and accesses the User Management section.
2. Fill in a form to create a new user account, submits it, and receives confirmation.
3. Access a list of user accounts, with options to search and filter based on specific criteria.
4. Select an account to edit, updates information, and submits changes, receiving a confirmation.
5. Choose to delete an account, confirm\ the action, and the system deletes the account and confirms completion.

Acceptance Criteria

- [ ]  Administrative portal provides secure access to the User Management section.
- [ ] New user accounts can be created with all required details.
- [ ] Administrator can search, filter, and view user accounts easily.
- [ ] Updates to user accounts can be made and are accurately reflected in the system.
- [ ] User accounts can be deleted with a confirmation step to prevent mistakes.
- [ ] The system maintains data integrity and updates the database correctly after each operation.
- [ ] Documentation for user management is comprehensive and easy to understand.
- [ ] All functionalities are covered by unit and integration tests.
- [ ] User account management operations are efficient, reflecting changes in real-time.

**Comment by matiakc** [comment]
![US4 Activity diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/5e183dcc-9c1e-47fd-9a79-e0ca73aad02e)

**Comment by matiakc** [comment]
![US4 Sequence diagram](https://github.com/sknt11/Orion-soen341projectW2024/assets/151582898/8e09e4af-f856-4443-a6c9-0107c9cd7517)
